import { ThemeProvider } from "@/components/ui/ThemeProvider";
import "./globals.css";
export const metadata = {
  title: "Floki",
  description: "Generated by create next app",

  icons: {
    icon: "/logo.png", // Make sure logo.png is in the public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
